baseURL: https://localaagroup.org/
title: Local Area

languageCode: en-us
theme: [aamod, mainroad]
sectionPagesMenu: main
paginate: 100
buildFuture: true

Params:
  description: Local Intergroup
  source: https://github.com/YOUR-PROJECT/YOUR-REPO/tree/master
  #mapapikey: <https://developers.google.com/maps/documentation/embed/get-api-key>
  #mapcenter: {lat: 43.536388, lng: -96.731667}
  #mapzoom: 10
  copyright: Local Intergroup
  phone: 123-456-7890
  logo:
    image: img/AAlogo.png
    title: Local AA Intergroup
  toc: true
  mainSections: [home, meetings, about, events]
  sidebar:
    single: right
    home: right
    widgets: [resources, eventsidemenu, aasites]
  widgets:

    resources:
      - title: Meeting Schedule
        url: /meeting-schedule.pdf
      - title: Big Book Online
        url: https://www.aa.org/bigbookonline/

    aasites:
      - title: A.A. Area 63 (S.D.)
        url: https://area63aa.org/
      - title: A.A. World Services
        url: https://www.aa.org/
      - title: A.A. Grapevine
        url: http://www.aagrapevine.org/

markup:
  goldmark:
    renderer:
      # Permit raw HTML in content
      unsafe: true

pdf-cols:
  aalist: 4
  anonlist: 2

pdf-blurbs:
  front: |
    \vskip 2ex {\footnotesize If you have changes to this directory, please write to:}
    \vskip 1ex {\large Local Area Intergroup\\
    P.O. Box 1\\
    City, ST 42024}
  alanon: |
    {\7pt Al-Anon members are people who are worried about someone with a drinking problem.}\\
    {\7pt\textbf{24-Hour Hotline:} (123) 456-7890}\\
    {\7pt\textbf{Al-Anon Information:} al-anon.org}
  resources: |
    {\7pt\textbf{Local Area:} localaagroup.org/meeting-times}\\
    {\7pt\textbf{South Dakota State:} www.area63.org}
  details: |
    \textbf{Local Area Intergroup}\\
    Meets at: Very Local AA\\
    {\6pt Every 2nd Sunday of the month at 4:30 PM}
